### ISSUE TITLE
nkeys building error

### ISSUE THREAD

**Issue by YoshieraHuang** [mnetship/ratsio#19]
When i build with rastio 0.3.0-alpha.1, an error about nkeys occurs:

   Compiling nkeys v0.0.8
error[E0599]: no method named `as_slice` found for struct `ed25519::Signature` in the current scope
   --> /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/nkeys-0.0.8/src/lib.rs:210:20
    |
210 |             Ok(sig.as_slice().to_vec())
    |                    ^^^^^^^^ method not found in `ed25519::Signature`

How can i solve it?

**Comment by YoshieraHuang** [comment]
zshell31:nkeys_update has fixed it. Hope to merge soon.
